
[extension]
id = "sieve"
name = "Sieve"
description = "Language support for Sieve email filtering language (RFC 5228) with Proton advanced features"
version = "0.1.0"
schema_version = 1
authors = ["Adam Smith <36318507+aRustyDev@users.noreply.github.com>"]
repository = "https://github.com/arustydev/zed-sieve"

# Languages supported by this extension
[languages.sieve]
name = "Sieve"
grammar = "sieve"
path_suffixes = [".sieve", ".sv"]
line_comment = "#"
block_comment = ["/*", "*/"]
auto_indent_using_last_non_empty_line = true

# Tree-sitter grammar configuration
[grammars.sieve]
repository = "https://github.com/aRustyDev/tree-sitter-sieve"
rev = "main"

# Language server configuration
[language_servers.sieve]
name = "Sieve Language Server"
languages = ["Sieve"]
