
# [extension]
id = "sieve"
name = "Sieve"
version = "0.1.0"
schema_version = 1
authors = ["Adam Smith <developer@gh.arusty.dev>"]
description = "Language support for Sieve email filtering language (RFC 5228) with Proton advanced features"
repository = "https://github.com/arustydev/zed-sieve"

# Tree-sitter grammar configuration
[grammars.sieve]
repository = "https://github.com/aRustyDev/tree-sitter-sieve"
rev = "main"

# Language server configuration
[language_servers.sieve]
name = "Sieve Language Server"
languages = ["Sieve"]
